CREATE TABLE public.positions
(
    "İd" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_positions PRIMARY KEY ("İd")
)

TABLESPACE pg_default;

ALTER TABLE public.positions
    OWNER to postgres;
	
CREATE TABLE public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(50) COLLATE pg_catalog."default" NOT NULL,
    isactive boolean NOT NULL DEFAULT false,
    CONSTRAINT pk_users PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.users
    OWNER to postgres;
-- Index: uk_users_email

-- DROP INDEX public.uk_users_email;

CREATE UNIQUE INDEX uk_users_email
    ON public.users USING btree
    (email COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE TABLE public.jobseekers
(
    userid integer NOT NULL,
    firstname character varying(50) COLLATE pg_catalog."default" NOT NULL,
    lastname character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nationalityid character(11) COLLATE pg_catalog."default" NOT NULL,
    dateofbirth date NOT NULL,
    CONSTRAINT pk_jobseekers PRIMARY KEY (userid),
    CONSTRAINT fk_jobseekers_users FOREIGN KEY (userid)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public.jobseekers
    OWNER to postgres;
-- Index: uk_jobseekers_nationalid

-- DROP INDEX public.uk_jobseekers_nationalid;

CREATE INDEX uk_jobseekers_nationalid
    ON public.jobseekers USING btree
    (nationalityid COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE TABLE public.employers
(
    userid integer NOT NULL,
    companyname character varying(100) COLLATE pg_catalog."default" NOT NULL,
    webaddress character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phonenumber character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_employers PRIMARY KEY (userid),
    CONSTRAINT fk_employers_users FOREIGN KEY (userid)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public.employers
    OWNER to postgres;

CREATE TABLE public.employees
(
    userid integer NOT NULL,
    positionid integer NOT NULL,
    CONSTRAINT pk_staff PRIMARY KEY (userid),
    CONSTRAINT fk_employees_positions FOREIGN KEY (positionid)
        REFERENCES public.positions ("İd") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_employees_users FOREIGN KEY (userid)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public.employees
    OWNER to postgres;



CREATE TABLE public.verificationemails
(
    id integer NOT NULL,
    userid integer NOT NULL,
    emaildate date NOT NULL,
    verificationcode character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_verificationemails PRIMARY KEY (id),
    CONSTRAINT fk_verificationemails_users1 FOREIGN KEY (userid)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public.verificationemails
    OWNER to postgres;
